In [1]:
import pandas as pd
from colors import rgb, hex
import numpy as np

In [2]:
df = pd.read_json("../Data/test.json", "r", encoding="utf8")
df.head()

<ipython-input-2-fc908862e1b9>:1: FutureWarning: Starting with Pandas version 2.0 all arguments of read_json except for the argument 'path_or_buf' will be keyword-only
  df = pd.read_json("../Data/test.json", "r", encoding="utf8")

,brand,brand_short,product,product_short,hex,H,S,V,L,group,shade
0,Maybelline,mb,Fit Me,fmf,f3cfb3,26,0.26,0.95,86,2,Fair Porcelain
1,Maybelline,mb,Fit Me,fmf,ffe3c2,32,0.24,1,92,2,Fair Ivory
2,Maybelline,mb,Fit Me,fmf,ffe0cd,23,0.2,1,91,2,Porcelain
3,Maybelline,mb,Fit Me,fmf,ffd3be,19,0.25,1,88,2,Natural Ivory
4,Maybelline,mb,Fit Me,fmf,bd9584,18,0.3,0.74,65,2,Ivory

In [3]:
tuple(hex(df['hex'][2]).rgb)

(255, 224, 205)

In [4]:
df['hex']

0      f3cfb3
1      ffe3c2
2      ffe0cd
3      ffd3be
4      bd9584
        ...
584    eecfba
585    e8c7b8
586    f0cbb9
587    e9c4b1
588    eabea1
Name: hex, Length: 589, dtype: object

In [49]:
print(df.loc[0,'hex'])

f3cfb3

In [8]:
df['hex'] = df['hex'].apply(lambda x: tuple(hex(x).rgb))

In [9]:
df['hex'][0][0]

243

In [10]:
df['hex'][0][1]

207

In [11]:
df['hex'][0][2]

179

In [12]:
red = []
green = []
blue = []

for i in df['hex']:
    red.append(i[0])
    green.append(i[1])
    blue.append(i[2])

In [13]:
df['red'] = red
df['green'] = green
df['blue'] = blue

In [14]:
df

,brand,brand_short,product,product_short,hex,H,S,V,L,group,shade,red,green,blue
0,Maybelline,mb,Fit Me,fmf,"(243, 207, 179)",26,0.26,0.95,86,2,Fair Porcelain,243,207,179
1,Maybelline,mb,Fit Me,fmf,"(255, 227, 194)",32,0.24,1,92,2,Fair Ivory,255,227,194
2,Maybelline,mb,Fit Me,fmf,"(255, 224, 205)",23,0.2,1,91,2,Porcelain,255,224,205
3,Maybelline,mb,Fit Me,fmf,"(255, 211, 190)",19,0.25,1,88,2,Natural Ivory,255,211,190
4,Maybelline,mb,Fit Me,fmf,"(189, 149, 132)",18,0.3,0.74,65,2,Ivory,189,149,132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,L'Oréal,lo,True Match,tms,"(238, 207, 186)",24,0.22,0.93,85,7,N4 Nude Beige,238,207,186
585,L'Oréal,lo,True Match,tms,"(232, 199, 184)",19,0.21,0.91,83,7,G5 Gold Cream,232,199,184
586,L'Oréal,lo,True Match,tms,"(240, 203, 185)",20,0.23,0.94,85,7,W6 Sun Beige,240,203,185
587,L'Oréal,lo,True Match,tms,"(233, 196, 177)",20,0.24,0.91,82,7,N7 Nude Amber,233,196,177
588,L'Oréal,lo,True Match,tms,"(234, 190, 161)",24,0.31,0.92,80,7,W7 Caramel Beige,234,190,161

In [89]:
example = (222.24678456591653 + 193.00401929260468 + 181.0803858520894)

In [91]:
df['test'] = example
df

,brand,brand_short,product,product_short,hex,H,S,V,L,group,red,green,blue,test
0,Maybelline,mb,Fit Me,fmf,"(243, 207, 179)",26.0,0.26,0.95,86,2,243,207,179,596.33119
1,Maybelline,mb,Fit Me,fmf,"(255, 227, 194)",32.0,0.24,1.00,92,2,255,227,194,596.33119
2,Maybelline,mb,Fit Me,fmf,"(255, 224, 205)",23.0,0.20,1.00,91,2,255,224,205,596.33119
3,Maybelline,mb,Fit Me,fmf,"(255, 211, 190)",19.0,0.25,1.00,88,2,255,211,190,596.33119
4,Maybelline,mb,Fit Me,fmf,"(189, 149, 132)",18.0,0.30,0.74,65,2,189,149,132,596.33119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,L'Oréal,lo,True Match,tms,"(238, 207, 186)",24.0,0.22,0.93,85,7,238,207,186,596.33119
621,L'Oréal,lo,True Match,tms,"(232, 199, 184)",19.0,0.21,0.91,83,7,232,199,184,596.33119
622,L'Oréal,lo,True Match,tms,"(240, 203, 185)",20.0,0.23,0.94,85,7,240,203,185,596.33119
623,L'Oréal,lo,True Match,tms,"(233, 196, 177)",20.0,0.24,0.91,82,7,233,196,177,596.33119
624,L'Oréal,lo,True Match,tms,"(234, 190, 161)",24.0,0.31,0.92,80,7,234,190,161,596.33119

In [93]:
df['rgbsum'] = df['red'] + df['green'] + df['blue']
df

,brand,brand_short,product,product_short,hex,H,S,V,L,group,red,green,blue,test,rgbsum
0,Maybelline,mb,Fit Me,fmf,"(243, 207, 179)",26.0,0.26,0.95,86,2,243,207,179,596.33119,629
1,Maybelline,mb,Fit Me,fmf,"(255, 227, 194)",32.0,0.24,1.00,92,2,255,227,194,596.33119,676
2,Maybelline,mb,Fit Me,fmf,"(255, 224, 205)",23.0,0.20,1.00,91,2,255,224,205,596.33119,684
3,Maybelline,mb,Fit Me,fmf,"(255, 211, 190)",19.0,0.25,1.00,88,2,255,211,190,596.33119,656
4,Maybelline,mb,Fit Me,fmf,"(189, 149, 132)",18.0,0.30,0.74,65,2,189,149,132,596.33119,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,L'Oréal,lo,True Match,tms,"(238, 207, 186)",24.0,0.22,0.93,85,7,238,207,186,596.33119,631
621,L'Oréal,lo,True Match,tms,"(232, 199, 184)",19.0,0.21,0.91,83,7,232,199,184,596.33119,615
622,L'Oréal,lo,True Match,tms,"(240, 203, 185)",20.0,0.23,0.94,85,7,240,203,185,596.33119,628
623,L'Oréal,lo,True Match,tms,"(233, 196, 177)",20.0,0.24,0.91,82,7,233,196,177,596.33119,606
624,L'Oréal,lo,True Match,tms,"(234, 190, 161)",24.0,0.31,0.92,80,7,234,190,161,596.33119,585

In [94]:
df['difference'] = np.abs(df['rgbsum'] - df['test'])
df

,brand,brand_short,product,product_short,hex,H,S,V,L,group,red,green,blue,test,rgbsum,difference
0,Maybelline,mb,Fit Me,fmf,"(243, 207, 179)",26.0,0.26,0.95,86,2,243,207,179,596.33119,629,32.66881
1,Maybelline,mb,Fit Me,fmf,"(255, 227, 194)",32.0,0.24,1.00,92,2,255,227,194,596.33119,676,79.66881
2,Maybelline,mb,Fit Me,fmf,"(255, 224, 205)",23.0,0.20,1.00,91,2,255,224,205,596.33119,684,87.66881
3,Maybelline,mb,Fit Me,fmf,"(255, 211, 190)",19.0,0.25,1.00,88,2,255,211,190,596.33119,656,59.66881
4,Maybelline,mb,Fit Me,fmf,"(189, 149, 132)",18.0,0.30,0.74,65,2,189,149,132,596.33119,470,126.33119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,L'Oréal,lo,True Match,tms,"(238, 207, 186)",24.0,0.22,0.93,85,7,238,207,186,596.33119,631,34.66881
621,L'Oréal,lo,True Match,tms,"(232, 199, 184)",19.0,0.21,0.91,83,7,232,199,184,596.33119,615,18.66881
622,L'Oréal,lo,True Match,tms,"(240, 203, 185)",20.0,0.23,0.94,85,7,240,203,185,596.33119,628,31.66881
623,L'Oréal,lo,True Match,tms,"(233, 196, 177)",20.0,0.24,0.91,82,7,233,196,177,596.33119,606,9.66881
624,L'Oréal,lo,True Match,tms,"(234, 190, 161)",24.0,0.31,0.92,80,7,234,190,161,596.33119,585,11.33119

In [77]:
df['difference'].mean()

146.18730803858654

In [72]:
df['difference'].argmin()

573

In [73]:
df.loc[573]

brand                   Colorbar
brand_short                   cb
product            Perfect Match
product_short                 pm
hex              (236, 195, 165)
H                           25.0
S                            0.3
V                           0.93
L                             82
group                          7
red                          236
green                        195
blue                         165
test                   596.33119
rgbsum                       596
difference               0.33119
Name: 573, dtype: object

In [82]:
df = df.drop(columns=['test', 'rgbsum', 'difference'])

In [15]:
df.to_csv('../Data/shades_updated.csv', index=False)

In [16]:
path = '../Data/shades_updated.csv'
df = pd.read_csv(path)
df

,brand,brand_short,product,product_short,hex,H,S,V,L,group,shade,red,green,blue
0,Maybelline,mb,Fit Me,fmf,"(243, 207, 179)",26.0,0.26,0.95,86,2,Fair Porcelain,243,207,179
1,Maybelline,mb,Fit Me,fmf,"(255, 227, 194)",32.0,0.24,1.00,92,2,Fair Ivory,255,227,194
2,Maybelline,mb,Fit Me,fmf,"(255, 224, 205)",23.0,0.20,1.00,91,2,Porcelain,255,224,205
3,Maybelline,mb,Fit Me,fmf,"(255, 211, 190)",19.0,0.25,1.00,88,2,Natural Ivory,255,211,190
4,Maybelline,mb,Fit Me,fmf,"(189, 149, 132)",18.0,0.30,0.74,65,2,Ivory,189,149,132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,L'Oréal,lo,True Match,tms,"(238, 207, 186)",24.0,0.22,0.93,85,7,N4 Nude Beige,238,207,186
585,L'Oréal,lo,True Match,tms,"(232, 199, 184)",19.0,0.21,0.91,83,7,G5 Gold Cream,232,199,184
586,L'Oréal,lo,True Match,tms,"(240, 203, 185)",20.0,0.23,0.94,85,7,W6 Sun Beige,240,203,185
587,L'Oréal,lo,True Match,tms,"(233, 196, 177)",20.0,0.24,0.91,82,7,N7 Nude Amber,233,196,177
588,L'Oréal,lo,True Match,tms,"(234, 190, 161)",24.0,0.31,0.92,80,7,W7 Caramel Beige,234,190,161

In [17]:
foundation_dictionary = df.to_dict(orient='records')

In [18]:
import pymongo

# Setup connection to mongodb
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)

# Select database and collection to use
db = client.foundation_db
foundation = db.foundation

In [19]:

foundation.insert_many(foundation_dictionary)

In [122]:
#222,193,181
df2 = df.loc[df['red'] <= 222]

In [128]:
df2 = df.loc[((df['red'] >= 220 & (df['red'] <= 242)) & (df['blue'] >= 137)) & (df['blue'] <= 141) & (df['green'] >= 179) & (df['green'] <= 183)]

In [129]:
df2

,brand,brand_short,product,product_short,hex,H,S,V,L,group,red,green,blue
51,bareMinerals,bm,barePRO,pro,"(222, 181, 139)",30.0,0.37,0.87,77,2,222,181,139
533,Shiseido,sh,Synchro Skin,ss,"(235, 182, 140)",27.0,0.40,0.92,78,6,235,182,140